##############################################################################
# Content
##############################################################################

# Link to a page that gives an overview of all your projects.
# This can be an external link (e.g., to you GitHub profile) or to another
# page within your website.
projects_url: /projects

# Configure the navigation menu.
# A pair 'Key: url' will result in a link to 'url' with the name 'Key' in the
# navigation menu. Optionally, you can add translations for the 'Key' in
# languages/*.yml
nav:
  home: /
  about: /about/
  articles: /archives/
  projects: projects_url
  search: /search/


# Links to your social media accounts.
# The keys should correspond to Fontawesome icon names 
# (see https://fontawesome.com/icons?d=gallery&s=brands);
# only 'mail' is an exception.
social_links:
  github: https://github.com/mehrad77/
  twitter: https://twitter.com/mehrad77/
  telegram: https://t.me/TheMalco/
  linkedin: https://www.linkedin.com/in/mehrad77/
  lastfm: https://www.last.fm/user/mehrad77
  medium: https://medium.com/@mehrad77
  steam-square: https://steamcommunity.com/id/mehrad77/
  spotify: https://open.spotify.com/user/mehrad77?si=KVaWDYU_TNS6gxm6wGG4Sw
  youtube: https://www.youtube.com/channel/UCniga7c5xQkl0qKXCDOxw1w
  instagram: https://instagram.com/mehrad77
  mail: mailto:mehrad77@gmail.com


# Customize the overview with the most recent blog posts on the index page.
# Options:
#   - show_all_posts: whether to show all available posts.
#   - post_count: whether to show only the x most recent posts.
posts_overview:
  show_all_posts: false
  post_count: 10


##############################################################################
# Look and Feel
##############################################################################

# Customize the logo (i.e., the cactus) in the header.
# Options:
#   - enabled: whether to show (true) or hide (false) the logo.
#   - width: width of the logo in pixel units
#   - height: height of the logo in pixel units
#   - url: where the logo can be found
#   - gravatar: whether to use your Gravatar as the logo
logo:
  enabled: true
  width: 70
  height: 70
  url: /images/logo.png
  gravatar: true

# Customize the favicons.
# Cactus supports a limited set of the three most important icons:
#   - desktop: The classic favion.ico file.
#   - android: A 192x192 PNG file.
#   - apple:  A 180x180 PNG file.
# These can be generated with http://realfavicongenerator.net/
# Options:
#   - url: where the icon can be found
#   - gravatar: whether to create a favicon from your Gravatar
favicon: 
  desktop:
    url: /images/favicon.ico
    gravatar: true
  android:
    url: /images/favicon-192x192.png
    gravatar: true
  apple:
    url: /images/apple-touch-icon.png
    gravatar: true

# The color scheme that should be used to highlight codeblocks.
# See source/css/_highlight for a list of all available color schemes.
highlight: xcode

# Set the color scheme.
# Available color schemes are 'dark', 'light', 'classic' and 'white'.
# Alternatively, add your own custom color scheme to source/css/_colors.
colorscheme: mehrad

# Maximal width of the page in rem units.
page_width: 60


##############################################################################
# Miscellaneous
##############################################################################

# Enable or disable the RSS feed.
rss: 

# Turn your web pages into graph objects (see http://ogp.me).
open_graph: 
  fb_app_id:
  fb_admins:
  twitter_id:
  google_plus:


##############################################################################
# Plugins
##############################################################################

# Fill in your Disqus Comments Shortname to enable Disqus comments.
disqus: 
  enabled: true
  shortname: mehrad77
#  shortname: mehrad77-de
#  shortname: mehrad77-fa
#  shortname: mehrad77-pe

# Fill in your Google Analytics tracking ID to enable Google Analytics.
google_analytics: 
  enabled: true
  id: UA-103618500-1

# Fill in your Baidu Analytics tracking ID to enable Baidu Analytics.
baidu_analytics:
  enabled: false
  id: 2e6da3c375c8a87f5b664cea6d4cb29c

# Fill in you Gravatar user id / email if you want to use your gravatar as the
# logo and/or favicons of you website.
gravatar:
  email: mehrad77@gmail.com